// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: go-sys-monitor-daemon.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatType int32

const (
	StatType_LOAD_AVERAGE        StatType = 0
	StatType_CPU_STATS           StatType = 1
	StatType_DISKS_LOAD          StatType = 2
	StatType_DISKS_STATS         StatType = 3
	StatType_NETWORK_TOP_TALKERS StatType = 4
	StatType_NETWORK_CONN_STATS  StatType = 5
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0: "LOAD_AVERAGE",
		1: "CPU_STATS",
		2: "DISKS_LOAD",
		3: "DISKS_STATS",
		4: "NETWORK_TOP_TALKERS",
		5: "NETWORK_CONN_STATS",
	}
	StatType_value = map[string]int32{
		"LOAD_AVERAGE":        0,
		"CPU_STATS":           1,
		"DISKS_LOAD":          2,
		"DISKS_STATS":         3,
		"NETWORK_TOP_TALKERS": 4,
		"NETWORK_CONN_STATS":  5,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_go_sys_monitor_daemon_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_go_sys_monitor_daemon_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{0}
}

type StatsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Interval        int64                  `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	AveragingPeriod int64                  `protobuf:"varint,2,opt,name=averaging_period,json=averagingPeriod,proto3" json:"averaging_period,omitempty"`
	StatTypes       []StatType             `protobuf:"varint,3,rep,packed,name=stat_types,json=statTypes,proto3,enum=gtpsapi.StatType" json:"stat_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *StatsRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *StatsRequest) GetAveragingPeriod() int64 {
	if x != nil {
		return x.AveragingPeriod
	}
	return 0
}

func (x *StatsRequest) GetStatTypes() []StatType {
	if x != nil {
		return x.StatTypes
	}
	return nil
}

type StatsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AveragingPeriod   int64                  `protobuf:"varint,2,opt,name=averaging_period,json=averagingPeriod,proto3" json:"averaging_period,omitempty"`
	LoadAverage       *LoadAverage           `protobuf:"bytes,3,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	CpuStats          *CPUStats              `protobuf:"bytes,4,opt,name=cpu_stats,json=cpuStats,proto3" json:"cpu_stats,omitempty"`
	DisksLoad         *DisksLoad             `protobuf:"bytes,5,opt,name=disks_load,json=disksLoad,proto3" json:"disks_load,omitempty"`
	DisksStats        *DisksStats            `protobuf:"bytes,6,opt,name=disks_stats,json=disksStats,proto3" json:"disks_stats,omitempty"`
	NetworkTopTalkers *NetworkTopTalkers     `protobuf:"bytes,7,opt,name=network_top_talkers,json=networkTopTalkers,proto3" json:"network_top_talkers,omitempty"`
	NetworkConnStats  *NetworkConnStats      `protobuf:"bytes,8,opt,name=network_conn_stats,json=networkConnStats,proto3" json:"network_conn_stats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatsResponse) GetAveragingPeriod() int64 {
	if x != nil {
		return x.AveragingPeriod
	}
	return 0
}

func (x *StatsResponse) GetLoadAverage() *LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

func (x *StatsResponse) GetCpuStats() *CPUStats {
	if x != nil {
		return x.CpuStats
	}
	return nil
}

func (x *StatsResponse) GetDisksLoad() *DisksLoad {
	if x != nil {
		return x.DisksLoad
	}
	return nil
}

func (x *StatsResponse) GetDisksStats() *DisksStats {
	if x != nil {
		return x.DisksStats
	}
	return nil
}

func (x *StatsResponse) GetNetworkTopTalkers() *NetworkTopTalkers {
	if x != nil {
		return x.NetworkTopTalkers
	}
	return nil
}

func (x *StatsResponse) GetNetworkConnStats() *NetworkConnStats {
	if x != nil {
		return x.NetworkConnStats
	}
	return nil
}

type LoadAverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load1Min      float64                `protobuf:"fixed64,1,opt,name=load1min,proto3" json:"load1min,omitempty"`
	Load5Min      float64                `protobuf:"fixed64,2,opt,name=load5min,proto3" json:"load5min,omitempty"`
	Load15Min     float64                `protobuf:"fixed64,3,opt,name=load15min,proto3" json:"load15min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAverage) Reset() {
	*x = LoadAverage{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAverage) ProtoMessage() {}

func (x *LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAverage.ProtoReflect.Descriptor instead.
func (*LoadAverage) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *LoadAverage) GetLoad1Min() float64 {
	if x != nil {
		return x.Load1Min
	}
	return 0
}

func (x *LoadAverage) GetLoad5Min() float64 {
	if x != nil {
		return x.Load5Min
	}
	return 0
}

func (x *LoadAverage) GetLoad15Min() float64 {
	if x != nil {
		return x.Load15Min
	}
	return 0
}

type CPUStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserMode      float64                `protobuf:"fixed64,1,opt,name=user_mode,json=userMode,proto3" json:"user_mode,omitempty"`
	SystemMode    float64                `protobuf:"fixed64,2,opt,name=system_mode,json=systemMode,proto3" json:"system_mode,omitempty"`
	Idle          float64                `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *CPUStats) GetUserMode() float64 {
	if x != nil {
		return x.UserMode
	}
	return 0
}

func (x *CPUStats) GetSystemMode() float64 {
	if x != nil {
		return x.SystemMode
	}
	return 0
}

func (x *CPUStats) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

type DisksLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskLoad      []*DiskLoad            `protobuf:"bytes,1,rep,name=disk_load,json=diskLoad,proto3" json:"disk_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksLoad) Reset() {
	*x = DisksLoad{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksLoad) ProtoMessage() {}

func (x *DisksLoad) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksLoad.ProtoReflect.Descriptor instead.
func (*DisksLoad) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *DisksLoad) GetDiskLoad() []*DiskLoad {
	if x != nil {
		return x.DiskLoad
	}
	return nil
}

type DiskLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tps           float64                `protobuf:"fixed64,2,opt,name=tps,proto3" json:"tps,omitempty"`
	KpsRead       float64                `protobuf:"fixed64,3,opt,name=kps_read,json=kpsRead,proto3" json:"kps_read,omitempty"`
	KpsWrite      float64                `protobuf:"fixed64,4,opt,name=kps_write,json=kpsWrite,proto3" json:"kps_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskLoad) Reset() {
	*x = DiskLoad{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskLoad) ProtoMessage() {}

func (x *DiskLoad) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskLoad.ProtoReflect.Descriptor instead.
func (*DiskLoad) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{5}
}

func (x *DiskLoad) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskLoad) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *DiskLoad) GetKpsRead() float64 {
	if x != nil {
		return x.KpsRead
	}
	return 0
}

func (x *DiskLoad) GetKpsWrite() float64 {
	if x != nil {
		return x.KpsWrite
	}
	return 0
}

type DisksStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskStats     []*DiskStats           `protobuf:"bytes,1,rep,name=disk_stats,json=diskStats,proto3" json:"disk_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisksStats) Reset() {
	*x = DisksStats{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisksStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisksStats) ProtoMessage() {}

func (x *DisksStats) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisksStats.ProtoReflect.Descriptor instead.
func (*DisksStats) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{6}
}

func (x *DisksStats) GetDiskStats() []*DiskStats {
	if x != nil {
		return x.DiskStats
	}
	return nil
}

type DiskStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MbUsagePct    uint32                 `protobuf:"varint,2,opt,name=mb_usage_pct,json=mbUsagePct,proto3" json:"mb_usage_pct,omitempty"`
	InUsagePct    uint32                 `protobuf:"varint,3,opt,name=in_usage_pct,json=inUsagePct,proto3" json:"in_usage_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskStats) Reset() {
	*x = DiskStats{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskStats) ProtoMessage() {}

func (x *DiskStats) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskStats.ProtoReflect.Descriptor instead.
func (*DiskStats) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{7}
}

func (x *DiskStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskStats) GetMbUsagePct() uint32 {
	if x != nil {
		return x.MbUsagePct
	}
	return 0
}

func (x *DiskStats) GetInUsagePct() uint32 {
	if x != nil {
		return x.InUsagePct
	}
	return 0
}

type NetworkTopTalkers struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtTopTalkers    []*ProtTopTalkers      `protobuf:"bytes,6,rep,name=prot_top_talkers,json=protTopTalkers,proto3" json:"prot_top_talkers,omitempty"`
	TrafficTopTalkers []*TrafficTopTalkers   `protobuf:"bytes,7,rep,name=traffic_top_talkers,json=trafficTopTalkers,proto3" json:"traffic_top_talkers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkTopTalkers) Reset() {
	*x = NetworkTopTalkers{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTopTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTopTalkers) ProtoMessage() {}

func (x *NetworkTopTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTopTalkers.ProtoReflect.Descriptor instead.
func (*NetworkTopTalkers) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkTopTalkers) GetProtTopTalkers() []*ProtTopTalkers {
	if x != nil {
		return x.ProtTopTalkers
	}
	return nil
}

func (x *NetworkTopTalkers) GetTrafficTopTalkers() []*TrafficTopTalkers {
	if x != nil {
		return x.TrafficTopTalkers
	}
	return nil
}

type ProtTopTalkers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prot          string                 `protobuf:"bytes,1,opt,name=prot,proto3" json:"prot,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Persent       float64                `protobuf:"fixed64,3,opt,name=persent,proto3" json:"persent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtTopTalkers) Reset() {
	*x = ProtTopTalkers{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtTopTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtTopTalkers) ProtoMessage() {}

func (x *ProtTopTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtTopTalkers.ProtoReflect.Descriptor instead.
func (*ProtTopTalkers) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{9}
}

func (x *ProtTopTalkers) GetProt() string {
	if x != nil {
		return x.Prot
	}
	return ""
}

func (x *ProtTopTalkers) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProtTopTalkers) GetPersent() float64 {
	if x != nil {
		return x.Persent
	}
	return 0
}

type TrafficTopTalkers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	DestPort      int32                  `protobuf:"varint,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Bps           float64                `protobuf:"fixed64,4,opt,name=bps,proto3" json:"bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficTopTalkers) Reset() {
	*x = TrafficTopTalkers{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficTopTalkers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficTopTalkers) ProtoMessage() {}

func (x *TrafficTopTalkers) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficTopTalkers.ProtoReflect.Descriptor instead.
func (*TrafficTopTalkers) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{10}
}

func (x *TrafficTopTalkers) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TrafficTopTalkers) GetDestPort() int32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *TrafficTopTalkers) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *TrafficTopTalkers) GetBps() float64 {
	if x != nil {
		return x.Bps
	}
	return 0
}

type NetworkConnStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TcpEstab       int32                  `protobuf:"varint,1,opt,name=tcp_estab,json=tcpEstab,proto3" json:"tcp_estab,omitempty"`
	TcpFinWait     int32                  `protobuf:"varint,2,opt,name=tcp_fin_wait,json=tcpFinWait,proto3" json:"tcp_fin_wait,omitempty"`
	TcpSynRcv      int32                  `protobuf:"varint,3,opt,name=tcp_syn_rcv,json=tcpSynRcv,proto3" json:"tcp_syn_rcv,omitempty"`
	ListeningSoket []*ListeningSoket      `protobuf:"bytes,4,rep,name=listening_soket,json=listeningSoket,proto3" json:"listening_soket,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NetworkConnStats) Reset() {
	*x = NetworkConnStats{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnStats) ProtoMessage() {}

func (x *NetworkConnStats) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnStats.ProtoReflect.Descriptor instead.
func (*NetworkConnStats) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkConnStats) GetTcpEstab() int32 {
	if x != nil {
		return x.TcpEstab
	}
	return 0
}

func (x *NetworkConnStats) GetTcpFinWait() int32 {
	if x != nil {
		return x.TcpFinWait
	}
	return 0
}

func (x *NetworkConnStats) GetTcpSynRcv() int32 {
	if x != nil {
		return x.TcpSynRcv
	}
	return 0
}

func (x *NetworkConnStats) GetListeningSoket() []*ListeningSoket {
	if x != nil {
		return x.ListeningSoket
	}
	return nil
}

type ListeningSoket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	User          string                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListeningSoket) Reset() {
	*x = ListeningSoket{}
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListeningSoket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListeningSoket) ProtoMessage() {}

func (x *ListeningSoket) ProtoReflect() protoreflect.Message {
	mi := &file_go_sys_monitor_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListeningSoket.ProtoReflect.Descriptor instead.
func (*ListeningSoket) Descriptor() ([]byte, []int) {
	return file_go_sys_monitor_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *ListeningSoket) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListeningSoket) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListeningSoket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListeningSoket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListeningSoket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

var File_go_sys_monitor_daemon_proto protoreflect.FileDescriptor

const file_go_sys_monitor_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1bgo-sys-monitor-daemon.proto\x12\agtpsapi\"\x87\x01\n" +
	"\fStatsRequest\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\x03R\binterval\x12)\n" +
	"\x10averaging_period\x18\x02 \x01(\x03R\x0faveragingPeriod\x120\n" +
	"\n" +
	"stat_types\x18\x03 \x03(\x0e2\x11.gtpsapi.StatTypeR\tstatTypes\"\xbf\x03\n" +
	"\rStatsResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10averaging_period\x18\x02 \x01(\x03R\x0faveragingPeriod\x127\n" +
	"\fload_average\x18\x03 \x01(\v2\x14.gtpsapi.LoadAverageR\vloadAverage\x12.\n" +
	"\tcpu_stats\x18\x04 \x01(\v2\x11.gtpsapi.CPUStatsR\bcpuStats\x121\n" +
	"\n" +
	"disks_load\x18\x05 \x01(\v2\x12.gtpsapi.DisksLoadR\tdisksLoad\x124\n" +
	"\vdisks_stats\x18\x06 \x01(\v2\x13.gtpsapi.DisksStatsR\n" +
	"disksStats\x12J\n" +
	"\x13network_top_talkers\x18\a \x01(\v2\x1a.gtpsapi.NetworkTopTalkersR\x11networkTopTalkers\x12G\n" +
	"\x12network_conn_stats\x18\b \x01(\v2\x19.gtpsapi.NetworkConnStatsR\x10networkConnStats\"c\n" +
	"\vLoadAverage\x12\x1a\n" +
	"\bload1min\x18\x01 \x01(\x01R\bload1min\x12\x1a\n" +
	"\bload5min\x18\x02 \x01(\x01R\bload5min\x12\x1c\n" +
	"\tload15min\x18\x03 \x01(\x01R\tload15min\"\\\n" +
	"\bCPUStats\x12\x1b\n" +
	"\tuser_mode\x18\x01 \x01(\x01R\buserMode\x12\x1f\n" +
	"\vsystem_mode\x18\x02 \x01(\x01R\n" +
	"systemMode\x12\x12\n" +
	"\x04idle\x18\x03 \x01(\x01R\x04idle\";\n" +
	"\tDisksLoad\x12.\n" +
	"\tdisk_load\x18\x01 \x03(\v2\x11.gtpsapi.DiskLoadR\bdiskLoad\"h\n" +
	"\bDiskLoad\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03tps\x18\x02 \x01(\x01R\x03tps\x12\x19\n" +
	"\bkps_read\x18\x03 \x01(\x01R\akpsRead\x12\x1b\n" +
	"\tkps_write\x18\x04 \x01(\x01R\bkpsWrite\"?\n" +
	"\n" +
	"DisksStats\x121\n" +
	"\n" +
	"disk_stats\x18\x01 \x03(\v2\x12.gtpsapi.DiskStatsR\tdiskStats\"c\n" +
	"\tDiskStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\fmb_usage_pct\x18\x02 \x01(\rR\n" +
	"mbUsagePct\x12 \n" +
	"\fin_usage_pct\x18\x03 \x01(\rR\n" +
	"inUsagePct\"\xa2\x01\n" +
	"\x11NetworkTopTalkers\x12A\n" +
	"\x10prot_top_talkers\x18\x06 \x03(\v2\x17.gtpsapi.ProtTopTalkersR\x0eprotTopTalkers\x12J\n" +
	"\x13traffic_top_talkers\x18\a \x03(\v2\x1a.gtpsapi.TrafficTopTalkersR\x11trafficTopTalkers\"T\n" +
	"\x0eProtTopTalkers\x12\x12\n" +
	"\x04prot\x18\x01 \x01(\tR\x04prot\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x18\n" +
	"\apersent\x18\x03 \x01(\x01R\apersent\"r\n" +
	"\x11TrafficTopTalkers\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1b\n" +
	"\tdest_port\x18\x02 \x01(\x05R\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03bps\x18\x04 \x01(\x01R\x03bps\"\xb3\x01\n" +
	"\x10NetworkConnStats\x12\x1b\n" +
	"\ttcp_estab\x18\x01 \x01(\x05R\btcpEstab\x12 \n" +
	"\ftcp_fin_wait\x18\x02 \x01(\x05R\n" +
	"tcpFinWait\x12\x1e\n" +
	"\vtcp_syn_rcv\x18\x03 \x01(\x05R\ttcpSynRcv\x12@\n" +
	"\x0flistening_soket\x18\x04 \x03(\v2\x17.gtpsapi.ListeningSoketR\x0elisteningSoket\"\x80\x01\n" +
	"\x0eListeningSoket\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol*}\n" +
	"\bStatType\x12\x10\n" +
	"\fLOAD_AVERAGE\x10\x00\x12\r\n" +
	"\tCPU_STATS\x10\x01\x12\x0e\n" +
	"\n" +
	"DISKS_LOAD\x10\x02\x12\x0f\n" +
	"\vDISKS_STATS\x10\x03\x12\x17\n" +
	"\x13NETWORK_TOP_TALKERS\x10\x04\x12\x16\n" +
	"\x12NETWORK_CONN_STATS\x10\x052M\n" +
	"\fStatsService\x12=\n" +
	"\bGetStats\x12\x15.gtpsapi.StatsRequest\x1a\x16.gtpsapi.StatsResponse\"\x000\x01B\fZ\n" +
	"./;grpcapib\x06proto3"

var (
	file_go_sys_monitor_daemon_proto_rawDescOnce sync.Once
	file_go_sys_monitor_daemon_proto_rawDescData []byte
)

func file_go_sys_monitor_daemon_proto_rawDescGZIP() []byte {
	file_go_sys_monitor_daemon_proto_rawDescOnce.Do(func() {
		file_go_sys_monitor_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_sys_monitor_daemon_proto_rawDesc), len(file_go_sys_monitor_daemon_proto_rawDesc)))
	})
	return file_go_sys_monitor_daemon_proto_rawDescData
}

var file_go_sys_monitor_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_go_sys_monitor_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_go_sys_monitor_daemon_proto_goTypes = []any{
	(StatType)(0),             // 0: gtpsapi.StatType
	(*StatsRequest)(nil),      // 1: gtpsapi.StatsRequest
	(*StatsResponse)(nil),     // 2: gtpsapi.StatsResponse
	(*LoadAverage)(nil),       // 3: gtpsapi.LoadAverage
	(*CPUStats)(nil),          // 4: gtpsapi.CPUStats
	(*DisksLoad)(nil),         // 5: gtpsapi.DisksLoad
	(*DiskLoad)(nil),          // 6: gtpsapi.DiskLoad
	(*DisksStats)(nil),        // 7: gtpsapi.DisksStats
	(*DiskStats)(nil),         // 8: gtpsapi.DiskStats
	(*NetworkTopTalkers)(nil), // 9: gtpsapi.NetworkTopTalkers
	(*ProtTopTalkers)(nil),    // 10: gtpsapi.ProtTopTalkers
	(*TrafficTopTalkers)(nil), // 11: gtpsapi.TrafficTopTalkers
	(*NetworkConnStats)(nil),  // 12: gtpsapi.NetworkConnStats
	(*ListeningSoket)(nil),    // 13: gtpsapi.ListeningSoket
}
var file_go_sys_monitor_daemon_proto_depIdxs = []int32{
	0,  // 0: gtpsapi.StatsRequest.stat_types:type_name -> gtpsapi.StatType
	3,  // 1: gtpsapi.StatsResponse.load_average:type_name -> gtpsapi.LoadAverage
	4,  // 2: gtpsapi.StatsResponse.cpu_stats:type_name -> gtpsapi.CPUStats
	5,  // 3: gtpsapi.StatsResponse.disks_load:type_name -> gtpsapi.DisksLoad
	7,  // 4: gtpsapi.StatsResponse.disks_stats:type_name -> gtpsapi.DisksStats
	9,  // 5: gtpsapi.StatsResponse.network_top_talkers:type_name -> gtpsapi.NetworkTopTalkers
	12, // 6: gtpsapi.StatsResponse.network_conn_stats:type_name -> gtpsapi.NetworkConnStats
	6,  // 7: gtpsapi.DisksLoad.disk_load:type_name -> gtpsapi.DiskLoad
	8,  // 8: gtpsapi.DisksStats.disk_stats:type_name -> gtpsapi.DiskStats
	10, // 9: gtpsapi.NetworkTopTalkers.prot_top_talkers:type_name -> gtpsapi.ProtTopTalkers
	11, // 10: gtpsapi.NetworkTopTalkers.traffic_top_talkers:type_name -> gtpsapi.TrafficTopTalkers
	13, // 11: gtpsapi.NetworkConnStats.listening_soket:type_name -> gtpsapi.ListeningSoket
	1,  // 12: gtpsapi.StatsService.GetStats:input_type -> gtpsapi.StatsRequest
	2,  // 13: gtpsapi.StatsService.GetStats:output_type -> gtpsapi.StatsResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_go_sys_monitor_daemon_proto_init() }
func file_go_sys_monitor_daemon_proto_init() {
	if File_go_sys_monitor_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_sys_monitor_daemon_proto_rawDesc), len(file_go_sys_monitor_daemon_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_sys_monitor_daemon_proto_goTypes,
		DependencyIndexes: file_go_sys_monitor_daemon_proto_depIdxs,
		EnumInfos:         file_go_sys_monitor_daemon_proto_enumTypes,
		MessageInfos:      file_go_sys_monitor_daemon_proto_msgTypes,
	}.Build()
	File_go_sys_monitor_daemon_proto = out.File
	file_go_sys_monitor_daemon_proto_goTypes = nil
	file_go_sys_monitor_daemon_proto_depIdxs = nil
}
